# Generated by Django 5.2.4 on 2025-07-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='name_quote',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
