# Generated by Django 5.2.4 on 2025-07-25 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_book_name_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='page',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
    ]
