# Generated by Django 5.2.4 on 2025-07-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_book_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='name_quote',
        ),
        migrations.AddField(
            model_name='quote',
            name='name_quote',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
