# Generated by Django 5.2.4 on 2025-07-25 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_remove_book_name_quote_quote_name_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='name_quote',
            new_name='name',
        ),
    ]
