# Generated by Django 5.2.4 on 2025-07-25 12:50

import journal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_rename_name_quote_quote_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='unique_id',
            field=models.IntegerField(default=journal.models.generate_unique_id, unique=True),
        ),
    ]
