# Generated by Django 5.2.4 on 2025-07-25 12:52

import journal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_book_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='unique_id',
            field=models.IntegerField(blank=True, default=journal.models.generate_unique_id, null=True, unique=True),
        ),
    ]
