# Generated by Django 5.2.4 on 2025-07-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_alter_book_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='unique_id',
            field=models.IntegerField(blank=True, default=40009, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='unique_id',
            field=models.IntegerField(blank=True, default=1771, editable=False, null=True, unique=True),
        ),
    ]
