# Generated by Django 5.2.4 on 2025-07-31 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_quote_unique_id_alter_book_unique_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='unique_id',
            field=models.IntegerField(blank=True, default=6673, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='unique_id',
            field=models.IntegerField(blank=True, default=83567, editable=False, null=True, unique=True),
        ),
    ]
