# Generated by Django 5.2.4 on 2025-07-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_book_user_quote_user_alter_book_unique_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='user',
        ),
        migrations.AlterField(
            model_name='book',
            name='unique_id',
            field=models.IntegerField(blank=True, default=2142, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='unique_id',
            field=models.IntegerField(blank=True, default=77520, editable=False, null=True, unique=True),
        ),
    ]
