# Generated by Django 5.2.4 on 2025-08-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_book_user_quote_user_alter_book_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='unique_id',
            field=models.IntegerField(blank=True, default=1936, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='unique_id',
            field=models.IntegerField(blank=True, default=50301, editable=False, null=True, unique=True),
        ),
    ]
